apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: <docker_account>/microservices-example-email-service:latest
          env:
            - name: PORT
              value: '3000'
            - name: MONGO_URI
              value: 'mongodb://email-service-mongo-svc:27020/emails'
            - name: MAILHOG_URI
              value: 'mailhog-svc'
---
apiVersion: v1
kind: Service
metadata:
  name: email-service-svc
spec:
  selector:
    app: email-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
